### ISSUE TITLE
No racial modifiers, heritage traits or the like after respec.

### ISSUE THREAD

**Issue by BrutaleBent** [BarleyFlour/RespecMod#1]

**Comment by BarleyFlour** [comment]
Which version, also please elaborate.

**Comment by BrutaleBent** [comment]
Example: Woljif - respeccing him removes racial traits, modifiers and background trait, and doesn't add them back.

Unlike the kingmaker respec mod that only removes things bound to classes/levelling themselves upon respec (I think...), this removes everything, and doesn't add them back.

**Comment by BarleyFlour** [comment]
Which version tho

**Comment by BrutaleBent** [comment]
1.1 ofcourse. ;)

**Comment by BarleyFlour** [comment]
Racial Traits, Modifiers and such should be fixed with 1.2, working on background traits for 1.3.

**Comment by BrutaleBent** [comment]
That's just effin' awesome, mate! Take your time, and know it's really appreciated. :)

Found another thing; Nenio's portrait changes, if you respec her - but since it's apperently buggy, and can happen anyways under other circumstances, so I'm not sure it has anything to do with your respec addon in the end - but now you know! :)

**Comment by BarleyFlour** [comment]
You would have to Re-Respec, the Nenio thing is a base game thing afaik.

**Comment by BarleyFlour** [comment]
Should be fixed as of 1.3.
