### ISSUE TITLE
Bug with Attributes - Critical

### ISSUE THREAD

**Issue by Shingam** [BarleyFlour/RespecMod#101]
I tried to respec Regill when he was level 6, but capable to lvlUP to 8. I had a bug, when I on lvl 4 (with bonus attribute) I have 0 points of bonus attributes and can't proceed further because screen tells that points are left. 

After this, I can not retrain him with NPC because this bug persists AND I can not lvlUP him because this screen with attributes pops up on any lvl.
 
![image](https://user-images.githubusercontent.com/91539788/135081205-fe069eb2-92b9-4b4c-9010-4aa0066ac965.png)

**Comment by megahell84** [comment]
I have the exact same situation, therefore I can't use the mod.

**Comment by megahell84** [comment]
The version 1.06.5 fixed the issue ! Thx BarleyFlour ;)
