### ISSUE TITLE
Full story companion respec is retaining original racial heritage selection options.

### ISSUE THREAD

**Issue by legallyinshane** [BarleyFlour/RespecMod#102]
Steps to reproduce:

Select companion (I chose Camellia)
Change Stats Slider to 25
Select Free Respec
Select Full Story Companion Respec
Select Retain Voice
Select Retain Portrait
Click Submit
Click Class 
Select Class (I chose Monk - Traditional)
Select Race (I chose Tiefling)

The heritage options listed are for Camellia's orginal race (half-elf)

**Comment by ramilos-creator** [comment]
the same thing with sosiel, you respecify the elf, there is an extra feature from the person

**Comment by BarleyFlour** [comment]
Fixed with v1.06.4
