### ISSUE TITLE
Freeze after respecing Aureshalae

### ISSUE THREAD

**Issue by Erorior** [BarleyFlour/RespecMod#107]
Hi!

I'm trying to respec Aureshalae, keeping original stats, backgrounds, portrait etc. However, each time the game freezes after I finish making choices for level 4 (the levelup screen vanishes and I'm left with a frozen image of the character and environment). Does this have something to do with her stats being abnormal for a starting level character, and is there a way around it? I have no other mods installed.

Best regards, and thanks for your hard work!

**Comment by Panda2111** [comment]
Found a way to fix this. Just do the 1° level, then go back and level her again normaly.

**Comment by Erorior** [comment]
> Found a way to fix this. Just do the 1° level, then go back and level her again normaly.

Ah thanks! I will try that!

**Comment by BarleyFlour** [comment]
Fixed with v1.06.5
