### ISSUE TITLE
0.80m Respec Button does not trigger an action

### ISSUE THREAD

**Issue by manilein** [BarleyFlour/RespecMod#11]
Hi as stated in the title, I guess the newest update of the Beta broke something. Please keep up your good work :)

0.80m Respec Button does not trigger an action

**Comment by BarleyFlour** [comment]
Are you sure you have enough gold? if so check the logs if there's anything in there.

**Comment by manilein** [comment]
Yes I had enough Gold, Funny I reverted to an older version of the mod and the mod was working again.

**Comment by BarleyFlour** [comment]
Can you send me your player.log file? you can find it by clicking "Logs" and then "open detailed log" in the ingame Mod interface

**Comment by XANi** [comment]
Here is mine
[Player.log](https://github.com/BarleyFlour/RespecMod/files/7101059/Player.log)
tried few options, (paid respec and free respec, both on wenduag, tried at level 2 and when I had level 1 + one level up pending)

**Comment by Lavantgarde2** [comment]
Same here, mod doesn't work for me

**Comment by BarleyFlour** [comment]
> Here is mine
> [Player.log](https://github.com/BarleyFlour/RespecMod/files/7101059/Player.log)
> tried few options, (paid respec and free respec, both on wenduag, tried at level 2 and when I had level 1 + one level up pending)

You're using an old version made for Beta 3, not the full release.
