### ISSUE TITLE
Some feats not removed when I respec

### ISSUE THREAD

**Issue by Vilacard** [BarleyFlour/RespecMod#118]
When respeccing, I noticed some feats weren't removed and I still had them afterwards. The ones I noticed were Indomitable Mount, Spirited Charge, and Vulpine Pounce. I also noticed I still had the mythic trickster tricks Persuasion 1 rank and Perception 1 rank.

I'm using the latest version of RespecMod, v1.06.6.

**Comment by ExtraMediumPizza** [comment]
I'm having a similar problem. I'm keeping the blood drinker and blood feaster racial feats, it also keeps Lifebonding Friendship with Azata which prevents me from picking the skill during a full respec.
