### ISSUE TITLE
Unable to select Oracle curse while respeccing MC.

### ISSUE THREAD

**Issue by pheonix99** [BarleyFlour/RespecMod#125]
When respeccing MC as oracle, cannot select curse.

Can confirm it's not toybox this time.

**Comment by pheonix99** [comment]
https://github.com/BarleyFlour/RespecMod/pull/126

This pull request fixes the oracle curse problem.

**Comment by BarleyFlour** [comment]
Fixed with v1.06.7 (pretty sure atleast)
