### ISSUE TITLE
Undead Companions retain Class Features

### ISSUE THREAD

**Issue by Cronos-988** [BarleyFlour/RespecMod#128]
I'm running Respec 1.06.6

When Respeccing Staunton Vhane and Delamere, I had some class features retained.

Staunton keeps all Domains he has had previous when respecing him as a Cleric multiple times.
To replicate: Give Staunton a Level of any Cleric class with a domain. Then Respec him, giving him a different domain. His spell book will include spells from both domains and list them as domain spells. No Domain abilities are rtained.

Delamere has kept her Study target ability, at a bonus of one.
To Replicate: Respec Delamere as any class that does not get Study Target, but does have Sneak attack. On inflicting a sneak attack, study target is applied. The ability does not show up anywhere (Neither in the menu nor in the abilities tab).

For both of these cases, no actual features are visible either in the game or via ToyBox.

**Comment by sztrzask** [comment]
I respec'ed Staunton into Cleric without any issues today.

Using latest 1.06.7 version.
