### ISSUE TITLE
Game thinks I have unspent ability points

### ISSUE THREAD

**Issue by Zimax1234** [BarleyFlour/RespecMod#13]
Hello!

Have tried to use the latest 1.02 version of the mod on a few characters in the Inn after the tutorial dungeon. Tried respecing my main character and each of the companions, each time the game will not let me advance beyond ability point assignment saying that I had unspent ability points, have tried multiple configurations of class/race/point values to proceed and nothing appeared to work. Additionally this occured on 25 point buy and a few other point buys I tested from 20-40.  

Thanks for all your hard work!

**Comment by RyoAtemi** [comment]
I'm having this issue also.

**Comment by templer10** [comment]
same.

**Comment by BarleyFlour** [comment]
Fixed with v1.02.1
