### ISSUE TITLE
Minor Issue

### ISSUE THREAD

**Issue by JamesKrolak** [BarleyFlour/RespecMod#139]
If I right click on the mod in UMM (the .exe, not the in game menu) and select Home Page for this mod, it takes me to a page that doesn't exist.  It goes to:  https://github.com/BarleyFlour/RespecMod/Releases.  Can you change that address to take someone to just https://github.com/BarleyFlour/RespecMod?

Super handy mod, by the way!  There are too many things not obvious with how the game elements work, so being able to respec whenever you want makes it so much more tolerable.

**Comment by BarleyFlour** [comment]
Fixed with 1.09.1, turns out github's links are case sensitive.

**Comment by JamesKrolak** [comment]
I never would have thought that was the issue.  Thanks for fixing that!
