### ISSUE TITLE
Multiple copies of items after respec

### ISSUE THREAD

**Issue by CosmicOwl7** [BarleyFlour/RespecMod#14]
using v1.02.1 Game just started, i respec seelah and it works fine but every item  she had, there is now about 40 copies of them in my inventory. no other mods in use.

**Comment by templer10** [comment]
same here

**Comment by amitpaz1** [comment]
getting this as well.

**Comment by CosmicOwl7** [comment]
Also after every level up for every character, multiple stacks of items keep appearing in the inventory

**Comment by ReaHe** [comment]
Same problem here

**Comment by BarleyFlour** [comment]
Fixed with 1.02.2
