### ISSUE TITLE
Cannot seem to install mod as of latest patch

### ISSUE THREAD

**Issue by Reginude** [BarleyFlour/RespecMod#142]
Hello, great mod, thank you for creating it. As of the latest patch I seem to be unable to install the mod. I am using the most up-to-date version and have tried deleting old remanants from the game's mod folder, but get stuck with a blank status within unity mod manager and the mod being added folder-wise into the game's mod folder, but not showing up in game. 

Character's I've used the mod on seem to have messed up levels/skill points when leveling up now. I assume I could fix if I had this mod, but am a bit stuck as is. Please adivse.

**Comment by BarleyFlour** [comment]
are you sure that Unity Mod Manager is properly installed?

**Comment by Reginude** [comment]
I believe it is - it works for the toybox and autobuff bot mods. Pretty sure I've reinstalled Unity and those other 2 mods without issue since this came up, but I can try again later today.

**Comment by Reginude** [comment]
Do you know if uninstalling/reinstalling unity would alter exist mod installations? Don't want to have to redo queues in auto-buff.

**Comment by BarleyFlour** [comment]
shouldnt alter them.

**Comment by Reginude** [comment]
You were correct, it did not later them (though I backed up the scipts just in case). Still no luck though. 
![image](https://user-images.githubusercontent.com/92412754/141868681-2968eb74-c817-4d22-8aeb-711846012aa3.png)
![image](https://user-images.githubusercontent.com/92412754/141868752-826a4b0f-32e0-470f-8535-4a910edcc48c.png)

**Comment by Reginude** [comment]
Adding my Unity log in case it is helpful.
![image](https://user-images.githubusercontent.com/92412754/141868928-dd2f9423-19b5-4f4e-897a-59cc0bb28bc7.png)

**Comment by BarleyFlour** [comment]
Looks like you're downloading the source code instead of the mod, try downloading RespecWrath.zip from here instead https://github.com/BarleyFlour/RespecMod/releases/tag/v1.09.2

**Comment by Reginude** [comment]
That was indeed the issue, thank you.
