### ISSUE TITLE
v1.10.0 - Game crashes or freezes when hitting "submit", characters suddenly level 20 for no reason.

### ISSUE THREAD

**Issue by stuffinhere** [BarleyFlour/RespecMod#149]
What the title says pretty much. Perhaps there's a conflict with Toybox.

This new version suddenly gave me characters level 20 and when trying to respec, the game either crashed or froze after hitting "submit".

Mods are:
Cleaner
No Film Grain
One feat per level
Toybox
Visual Adjustments

The mod was working fine before the update.

**Comment by ForbAvalon** [comment]
I faced the same error like you.
Choose a option will not let it level up to 20 but no extra point will be added.
I will try the former ver and see if it work well.
