### ISSUE TITLE
'Attribute Selection' Icons on Character sheet, how to remove?

### ISSUE THREAD

**Issue by ptd3v** [BarleyFlour/RespecMod#156]
This mod adds weird icons on the character screen, how do I remove them? Not sure why they're here, just wanted a respec mod.

![download](https://user-images.githubusercontent.com/102877038/161397826-13c24498-9db2-4545-a151-f5b08013c17b.jpg)

**Comment by Trebuidoi** [comment]
Just created an account to tell you that if you disable the mod, it will go away. Unless you are respecing multiple times per game session, it isn't too much of annoyance enabling it only when you need it.

**Comment by 500kguser** [comment]
Hey! Thanks for the reply, but when I disable the mod, the respeced characters regain their previous classes and the level up process goes crazy so I need to keep it on permanently :(
