### ISSUE TITLE
Mod not loading(Mod version 1.06.6, Game version 2.1.0w)

### ISSUE THREAD

**Issue by qwertyduck** [BarleyFlour/RespecMod#193]
After looking into the log, the mod seems to me looking for a file called "RespecModBarley.dll" which it cannot find.

> [RespecModBarley] Version '1.06.6'. Loading.
> [RespecModBarley] [Error] File 'D:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods\RespecModBarley\RespecModBarley.dll' not found.
> [RespecModBarley] Loading time 0.00 s.

**Comment by BarleyFlour** [comment]
Old mod version.
