### ISSUE TITLE
Update 2.1.2d stops Respec from commiting changes

### ISSUE THREAD

**Issue by CasDragon** [BarleyFlour/RespecMod#201]
Brought to my attention from Minsc#8195 in the Discord

On the latest game version (2.1.2d), Respec will load the character gen  screen, but not commit the changes to the character. 

[GameLogFull.txt](https://github.com/BarleyFlour/RespecMod/files/11160546/GameLogFull.txt)

**Comment by patrikucarlsson** [comment]
Same here!
Just add comment, in order to say that CasDragon is not the only one.
I have only three mods installed.
