### ISSUE TITLE
currently respec function doesn't work mod version 1.10.16 and Game Version 2.2.0as

### ISSUE THREAD

**Issue by Norrorin** [BarleyFlour/RespecMod#219]
with hitting respec button Character creation screen doesn't start and lvl isn't set to 0.

Level -1 function  is working properly (until lvl 1) 

For Mystic both functions are working, fully reset and single lvl down

**Comment by bmardiney** [comment]
I somehow got it to work eventually (on the 6th or so try, hitting the tabs at the top finally populated the fields). However, in the Through the Ashes DLC, when you try to retrain mercenary companions (I was trying to give them all 25 ability points), as soon as the retrain is done, they disappear from the party (both the portrait and the model). The mod still sees them as active but the game itself doesn't seem to. Perhaps they got shoved into a different category?

**Comment by Norrorin** [comment]
![Bild_2023-11-22_144320095](https://github.com/BarleyFlour/RespecMod/assets/151689215/ed659676-19ed-47cb-b718-4511b70e96a4)
I've tried several times in different saves, maingame and through the ashes by submitting the fully respec nothing hapens

**Comment by zarfleen** [comment]
Starting a new game suffers from a similar problem where the portraits etc tabs aren't populating, and this appears to be more of a symptom with Toy Box than respec mod.  With nothing but Toy Box enabled, I get the same empty tabs as when trying to respec, so potentially an issue with Toy Box causing some of these problems.

**Comment by Norrorin** [comment]
hmm, I'havent ever installed toy box, just bubble buffs and allow modded achievements, question is does fully respec  work with this version for anyone?

**Comment by BarleyFlour** [comment]
Could you send your log files from "%appdata%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous", namely "GameLogFull.txt" and "Player.log"

**Comment by bmardiney** [comment]
I just deleted all mods except the updated Toybox, no film grain, achievements unlocked, and this mod. It still removes respecced companions. I also tried it after uninstalling Toybox, same result.
[Player.log](https://github.com/BarleyFlour/RespecMod/files/13445207/Player.log)
[GameLogFull.txt](https://github.com/BarleyFlour/RespecMod/files/13445208/GameLogFull.txt)

**Comment by Norrorin** [comment]
Thanks BarleyFlour I've checked the file by myself and found the issue, it was a non unitymod about the backgrounds I've installed somewhere end of 2021, after deleting it, fully respec works, just respec of mercs from through the ashes alignment is restricted to true neutral with the respec, which doesn't allow monks, palladin etc
![image](https://github.com/BarleyFlour/RespecMod/assets/151689215/1300b5e9-23b2-4713-a4ae-6e801ce131d9)
