### ISSUE TITLE
Woljif recruitment

### ISSUE THREAD

**Issue by Syntaxxxxxx** [BarleyFlour/RespecMod#25]
Version 1.2.2

When first recruiting Woljif (my MC is level 3) he's in a bugged state with 1HP and a prompt to level him up. Trying to do so results in one of two thing;

Blank level up screen, when exiting this your main character gets replaced with Woljif, breaking the game down the line.
Instant game over over, "party has been defeated".

I initially thought this was a game bug, but i uninstalled the mod and that remedied the issue.

**Comment by Narc0med** [comment]
Same issues with Delamere

**Comment by BarleyFlour** [comment]
Fixed with v1.05.1.
