### ISSUE TITLE
Respec bug for some class

### ISSUE THREAD

**Issue by Codetalker1988** [BarleyFlour/RespecMod#31]
If I play wizard build  to Arcane Trickster, when I respec and build my character with the same way, at arcane trickster lvl1,  I can't choose wizard spell book anymore and can't access the arcane trickster with wizard.

Same problem for Daeran's class Oracle 
If I respec an oracle with the additional spells 'cure spell' , I can only choose 'inflict spell' at Oracle lvl1 after respec.

**Comment by BarleyFlour** [comment]
Should be fixed with v1.02.3
