### ISSUE TITLE
No Deity Option for Full Companion Respec

### ISSUE THREAD

**Issue by Waylander00** [BarleyFlour/RespecMod#33]
There is no option to chose your deity which completely locks out any cleric/paladin choices past level 1.   If  you could update this in the future it would be greatly appreciated.

Or if I'm a moron and doing something wrong I'm open to corrections.  I tried to respec just the deity/background but I want to change the picture of companions so that I can still do their storyline as well, which that does not allow.

Thank you!

**Comment by BarleyFlour** [comment]
fixed with v1.02.3
