### ISSUE TITLE
Taking two-weapon fighting feat after respec causing extra attacks to appear

### ISSUE THREAD

**Issue by Anderson-P** [BarleyFlour/RespecMod#34]
After respecing Woljif and making very minor changes to his stat allocation, I am receiving an extra attack for his offhand weapon as if he had improved two weapon fighting.

Only have the regular twf feat at level 3. All feats left the same as his default when recruited. His BaB is being displayed as 2.

I also received the tutorial for iterative attacks as if he had reached BaB 6.
It's as if the phantom iterative attack is somehow being applied to his off hand.

Upon further testing a a similar thing happened after respecing Wenduag and taking the basic twf feat.
An iterative attack for her off-hand after respecing at lvl 3.

**Comment by CosmicOwl7** [comment]
I can confirm this, after respeccing wenduag and i give her two weapons the penalties she has are only -2 like if she had two weapon fighting and if i then take twf it gives her an extra attack like if it was improved twf, it seems respeccing them gives them the twf  feat in the background from the start.

**Comment by Zexor1** [comment]
Same, twf benefits on characters after a respec.

**Comment by bVanHertum** [comment]
Can confirm this as well - saw it now on Regill and Woljif both. Better yet, if you _do_ take Improved TWF, you'll get yet another additional attack, as if you took Greater TWF too.

**Comment by Anderson-P** [comment]
This issue seems to be resolved in your latest update. Thanks for all your hard work!
