### ISSUE TITLE
Companions autorespec upon joining

### ISSUE THREAD

**Issue by BrutaleBent** [BarleyFlour/RespecMod#4]
Maybe it's intended, but it would be nice if it was a toggle in the respec menu! ;)

**Comment by BarleyFlour** [comment]
Yeah its an unintended consequence of how i patch the library, i'm working on it rn.

**Comment by BarleyFlour** [comment]
Sorta fixed with 1.9, they wont get autorespecced unless you have respecced them in the same session (e.g getting them, respeccing them, then loading to before you got them and then getting them again without restarting the game)

**Comment by BrutaleBent** [comment]
Guess it no real news, but mod doesn't load with the new beta patch! :)

**Comment by BarleyFlour** [comment]
fixed with 2.0.
