### ISSUE TITLE
Can't Change Deity of Story Characters

### ISSUE THREAD

**Issue by Velgus** [BarleyFlour/RespecMod#42]
Attempting to respec Lann to change his Deity. I do have the "Choose Background/Deity" box checked, and it does allow me to change his Background, but not his Deity. Confirmed on Seelah (although I don't want to change hers) just for testing as well.

On the latest mod version (1.05).

**Comment by BarleyFlour** [comment]
This is an issue specifically with atheist companions and it is being looked at.

**Comment by BarleyFlour** [comment]
Fixed with 1.05.2
