### ISSUE TITLE
Recruited Greybor after installing mod who started at lvl 0 and corrupts save

### ISSUE THREAD

**Issue by Json-x-ly** [BarleyFlour/RespecMod#43]
Didn't even notice the issue until I threw him into my party to go do the dragon quest. When I attempted to level him up, I noticed he had 1hp and no weapon. His gear actually appeared in my inventory, which should have been my first hint. 

Attempting to level him up prompts to choose a portrait and race before his class. Cancelling/completing the character customization seams to either overwrite the main PC or copy Greybor in the party.

might be related to #17?

I'll try and update later with logs and some screenshots/saves

**Comment by Velgus** [comment]
Same here with the latest version when recruiting Woljif.

**Comment by Havoclivekiller** [comment]
I can confirm having this problem.

**Comment by Json-x-ly** [comment]
I can at least verify that if you disable the mod, restart, and reload a save before you recruit, it doesn't screw up after recruitment. 

Took me about 40 minutes of backtracking to verify. 😢

**Comment by BarleyFlour** [comment]
Fixed with v1.05.1.
