### ISSUE TITLE
Preserving alignment choices / More respec options for MC

### ISSUE THREAD

**Issue by vikigenius** [BarleyFlour/RespecMod#44]
MC respec needs more options. Right now if i want to just change a few feat selections/skill points, I have to reset the whole thing including stuff like gender and all of my alignment choices are lost.

Is there any way to add an option to preserve things like alignment choices?

**Comment by Greevee** [comment]
That would be awesome! Missing that too. 
Great Mod.

**Comment by alexanderwalters89** [comment]
Well, I built a fork that does most of this at https://github.com/alexanderwalters89/RespecMod.

Keeps alignment history, name, birthday, and voice, and loads the race and gender in as starting configuration.

You can still change the gender and race and I couldn't find a way to actually lock them as opposed to loading defaults that doesn't break the character model completely.

Couldn't preserve any appearance settings either. 

If BarleyFlour wants to merge this in, feel free, just mention me in the readme or something.

**Comment by BarleyFlour** [comment]
Added in 1.06.0 thanks to Pheonix99.
