### ISSUE TITLE
Azata Path Aivu

### ISSUE THREAD

**Issue by Demixt** [BarleyFlour/RespecMod#48]
Recieving Aivu or Respeccing mc (full or just myhic) with azata path makes her a normal level 1 animal companion instead of the level 10 Havoc Dragon mythic path version.
incase others have the issue temp Workaround: Respec > choose 1 level/first mythic > save > uninstall mod > relaunch > finish respeccing > relaunch with mods.

**Comment by BarleyFlour** [comment]
If you could send me a save before respeccing w/ Aivu so i can test i can try to fix it.

**Comment by Demixt** [comment]
[Manual_33_Drezen__18_Kuthona__XII__4715__15_15_39.zip](https://github.com/BarleyFlour/RespecMod/files/7145944/Manual_33_Drezen__18_Kuthona__XII__4715__15_15_39.zip)

**Comment by BarleyFlour** [comment]
Fixed with 1.05.3
