### ISSUE TITLE
Background glitched when respeccing main character

### ISSUE THREAD

**Issue by giorigor** [BarleyFlour/RespecMod#5]
Mod version: 2.2

When you respec your main character, the original background choice appears grayed out, as if it was selected before. Sometimes this also happen to the heritage selection.

![image](https://user-images.githubusercontent.com/10777906/118303175-851bae80-b4bb-11eb-998f-0c1ad7ffa7b9.png)

All other mods were disabled and the game was restarted before loading the save file.

**Comment by BarleyFlour** [comment]
I can recreate the background selection, but i dont seem to be able to recreate the heritage selection bug, could you be more specific with how exactly the heritage selection bug happens?

**Comment by giorigor** [comment]
When the heritage bug happened I still hadn't respecd my character, just tried leveling it up normally with the mod turned on. It treated the level-up screen as a character respec, and both heritage and background were "already selected".

**Comment by BarleyFlour** [comment]
I dont seem to be able to reproduce it, what race and class were you?

**Comment by giorigor** [comment]
My bad, this happens if I respec but then close the level up screen, then try leveling up normally. I think this is unavoidable, since the respec resets the character to level "0", and I shouldn't be doing this after pressing the respec button.

[Print is here, if you want to check it out though.](https://user-images.githubusercontent.com/10777906/118313287-ebf39480-b4c8-11eb-95b5-d9c74d81e772.png)

**Comment by BarleyFlour** [comment]
The background thing is fixed in 2.2.1.

**Comment by BarleyFlour** [comment]
The issue with canceling the respec should be fixed in 2.3.
