### ISSUE TITLE
game version 1.0.0s vs 1.0.0 mod don't load

### ISSUE THREAD

**Issue by anc3stral** [BarleyFlour/RespecMod#55]
when i tried to load mod in game logs say that he load 0/0 mod probably becasue he read incorrect version of the game 1.0.0s vs 1.0.0(that he looking for i supose).

Any workaround?

Thanks a lot!

**Comment by KB-93** [comment]
You would need to build this repo to use the mod.

**Comment by anc3stral** [comment]
Loving you!
This works like a charm, thanks a lot!
