### ISSUE TITLE
aivu (azata dragon companion) bug?

### ISSUE THREAD

**Issue by usernameisnotavailable123** [BarleyFlour/RespecMod#57]
Aivu starts spawning out of the map after a respec.
Also, I read that I should be able to talk to her in the citadel, but instead she's just treated as a **normal animal companion**. She spawns in the center of the room, instead of the area entrance where other characters are.
I didn't change the mythic path selection (azata).

**Comment by usernameisnotavailable123** [comment]
duplicate

**Comment by BarleyFlour** [comment]
Fixed with 1.05.3
