### ISSUE TITLE
Causing new or reloaded companions to respec to 0, stuck at level 1

### ISSUE THREAD

**Issue by AsmodeusUltima** [BarleyFlour/RespecMod#59]
Okay, this has happened most with the Triceratops companion from the figurine every time the bearer levels up (and therefore the triceratops recalculates and reloads), but also happened to Greybor. The affected companion has 1/1 hp and no class, ready to level up. Allows one to choose class (which, for the triceratops, is not supposed to be allowed) and all 1st level features. After leveling to 1, there is no longer a choice to level them further. This has been happening every time I level for the last few days, would disable UMM, load game, save with the properly leveled companion, reenable UMM, and play from there. Finally decided to try disabling mods one by one to determine which was causing the issue and this one was the winner.

**Comment by BarleyFlour** [comment]
Fixed with 1.05.3
