### ISSUE TITLE
Arueshalae respec Bug ability points

### ISSUE THREAD

**Issue by izu235** [BarleyFlour/RespecMod#62]
Hi,
I respecc Arueshalae at Level 8 an kept her originally stats. But at leveling her up to 9, she got 57 ability points to spent and a max cap of level 17. 

Is there a way to fix this?

Best regards

**Comment by BarleyFlour** [comment]
Are you using any other mods?

**Comment by izu235** [comment]
I used ToxBox, but disabled it. I Respect with both mods enabled and then deaktivated the mods. Then i got a levelup and i got so much ability points.

**Comment by izu235** [comment]
Ok, it inly is the case if i disbale your mod. I thought i can respecc, and then disable the mod

**Comment by BarleyFlour** [comment]
Unfortunately due to the way the game handles character levels of story companions you need to keep the mod on
