### ISSUE TITLE
Game freezes after respec

### ISSUE THREAD

**Issue by lucdatuv** [BarleyFlour/RespecMod#75]
Hi,

The game fully freezes after respeccing. I have no idea what I can do to fix this issue, but it means at current I cannot respec

**Comment by Pheace** [comment]
I get this too. The game unfreezes again if you start a normal levelup (by clicking the + icon on someone's portrait) and then back out of it. So for now I'd suggest leaving a party member/pet with a spare unused level till it is fixed

**Comment by Fable1991** [comment]
I had this issue but I just quick-saved then quick-loaded and it was fine.

**Comment by Amariithynar** [comment]
If it's the freeze I'm thinking of- it's something to do with the game itself, NOT the mod (as in they know it's an issue with respeccing in the unmodded game even), and you can fix it just by hitting C or I and then hitting it again to back out of it; everything will be right after that.

**Comment by BarleyFlour** [comment]
fixed with v1.06.1
