### ISSUE TITLE
Animal companion can't choose right class

### ISSUE THREAD

**Issue by lizkes** [BarleyFlour/RespecMod#8]
with newest version of this mod, the class selection interface of animal companion is broken.
the class selection interface of the animal companion from ranger lvl4 feat looks like this:
![图片](https://user-images.githubusercontent.com/20457790/126059682-b29194b4-ef3c-4f9c-8f41-546132440411.png)

**Comment by BarleyFlour** [comment]
I dont seem to be able to recreate this, if i respec a companion into ranger and get them to level 4 their animal companion works just fine. Could you explain how you can recreate it?

**Comment by lizkes** [comment]
I can’t reproduce this bug now. After reloading the save, the bug disappeared. Anyway, if I find a way to reproduce it, I will reopen this issue.
