### ISSUE TITLE
Respec not being applied. Even after leveling is finished companion is still level 1.

### ISSUE THREAD

**Issue by vikigenius** [BarleyFlour/RespecMod#83]
Just tried to respec Lann.

I click Respec and finishing levelling up all the levels. Then the UI closes automatically, but if I click Lann's portrait he is still showing as Level 1.

Reproduced with Ember as well. Also reproduced in multiple saves. One in Act 1 (before any Mythics, at Level 5) and another in Act 3 (at level 10).

**Comment by BarleyFlour** [comment]
Should be fixed with v1.06.1
