### ISSUE TITLE
after 1.06.2 cant chooese deity on companions

### ISSUE THREAD

**Issue by templer10** [BarleyFlour/RespecMod#89]
just what it says. 

ty

**Comment by ZexorC** [comment]
using last version of game and 1.06.2 the deity that i previously choose in respecced companions dissapear and i can't choose another one if i respecc again

**Comment by Mozgoth** [comment]
+1

**Comment by grimwall** [comment]
Same

**Comment by ramilos-creator** [comment]
+ 1 Same

**Comment by BarleyFlour** [comment]
Fixed with 1.06.3
