### ISSUE TITLE
racial mods doesnt show up, BAB is still stacking, cant see char in portrait 

### ISSUE THREAD

**Issue by templer10** [BarleyFlour/RespecMod#9]
hi - something seems very very wrong. 1.01.1 was fine but in the newer version BAB is back to stacking  and when respecing any companion racial mods arent present.

**Comment by templer10** [comment]
but if i got back to 1.01.1 cant select traits/aligment.

**Comment by BarleyFlour** [comment]
This is an issue where i made a mistake leading to null reference exception, will be fixed shortly.
