### ISSUE TITLE
Nenio

### ISSUE THREAD

**Issue by Neutralus1492** [BarleyFlour/RespecMod#91]
I picked up Nenio in town and headed over to the library to save a really old elf.  When I got there Nenio was my primary character and my primary Character took Nenio's spot.  Attempted to reload the game and different saves but I don't have one before I picked up Nenio and she is now the party leader.  I'm going to have to restart.

**Comment by foxagonal** [comment]
Similar thing happened to me. When I recruited Nenio, she had 1 HP and was ready to level up. But the level up interface was blank and couldn't be done. Then when I entered the defender's heart, Nenio was the new "leader" off in some dark corner of the map, and Hulrun died inexplicably.

**Comment by foxagonal** [comment]
I just ran into the same issue with Daeren while the mod was running. Though Hulrun still died somehow at the camp even after I reloaded on an old save without the mod active. So I'm really not sure what's up with that...

**Comment by BarleyFlour** [comment]
You need to update the Mod.

**Comment by Neutralus1492** [comment]
I have the most up to date mod.  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: BarleyFlour ***@***.***> Date: 9/23/21  8:57 AM  (GMT-05:00) To: BarleyFlour/RespecMod ***@***.***> Cc: Neutralus1492 ***@***.***>, Author ***@***.***> Subject: Re: [BarleyFlour/RespecMod] Nenio (#91) 
You need to update the Mod.

**Comment by BarleyFlour** [comment]
Do you have 1.06.2?

**Comment by foxagonal** [comment]
I do now, and it works fine. I didn't realize that 1.06.2 had been released
when I posted about the stuff. My bad!

**Comment by BarleyFlour** [comment]
Happy to help.
