### ISSUE TITLE
Problem with story companion respecc option with Daeran

### ISSUE THREAD

**Issue by gouldilox** [BarleyFlour/RespecMod#95]
The character creator forces me to select aasimar heritage two times.  Basically you select a race, and then it makes select another race, so you are forced to get the benefits from two seperate races or heritages.  I have the most recent version of the mod.  When you select a race the chraacter creator automatically prompts you to select a heritage.  But after that step, the mod makes you select an additional heritage.  The mod shouldn;t include the step of picking a heritage since the character creator automatically opens the heritage option after selecting the race.

**Comment by Mozgoth** [comment]
Recommendation: Download ToyBox and there is an option to remove feats, abilities, race bonuses, etc
Not a solution but worse is nothing.
I used for example to remove sacred weapon ability from warpriest.

**Comment by icereach** [comment]
To add, this seems to happen to every race except Human, for any Companion character.

**Comment by BarleyFlour** [comment]
Fixed with v1.06.4
